'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlySatteliteWeather.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 {
        '''&quot;110000&quot;:&quot;北京市&quot;,
        '''&quot;110101&quot;:&quot;东城区&quot;,
        '''&quot;110102&quot;:&quot;西城区&quot;,
        '''&quot;110105&quot;:&quot;朝阳区&quot;,
        '''&quot;110106&quot;:&quot;丰台区&quot;,
        '''&quot;110107&quot;:&quot;石景山区&quot;,
        '''&quot;110108&quot;:&quot;海淀区&quot;,
        '''&quot;110109&quot;:&quot;门头沟区&quot;,
        '''&quot;110111&quot;:&quot;房山区&quot;,
        '''&quot;110112&quot;:&quot;通州区&quot;,
        '''&quot;110113&quot;:&quot;顺义区&quot;,
        '''&quot;110114&quot;:&quot;昌平区&quot;,
        '''&quot;110115&quot;:&quot;大兴区&quot;,
        '''&quot;110116&quot;:&quot;怀柔区&quot;,
        '''&quot;110117&quot;:&quot;平谷区&quot;,
        '''&quot;110118&quot;:&quot;密云区&quot;,
        '''&quot;110119&quot;:&quot;延庆区&quot;,
        '''&quot;120000&quot;:&quot;天津市&quot;,
        '''&quot;120101&quot;:&quot;和平区&quot;,
        '''&quot;120102&quot;:&quot;河东区&quot;,
        '''&quot;120103&quot;:&quot;河西区&quot;,
        '''&quot;120104&quot;:&quot;南开区&quot;,
        '''&quot;120105&quot;:&quot;河北区&quot;,
        '''&quot;120106&quot;:&quot;红桥区&quot;,
        '''&quot;120110&quot;:&quot;东丽区&quot;,
        '''&quot;120111&quot;:&quot;西青区&quot;,
        '''&quot;120112&quot;:&quot;津南区&quot;,
        '''&quot;120113&quot... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property city() As String
            Get
                Return ResourceManager.GetString("city", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 上海上海,121.48,31.22|
        '''上海嘉定,121.24,31.4|
        '''上海宝山,121.48,31.41|
        '''上海川沙,121.7,31.19|
        '''上海南汇,121.76,31.05|
        '''上海奉贤,121.46,30.92|
        '''上海松江,121.24,31|
        '''上海金山,121.16,30.89|
        '''上海青浦,121.1,31.15|
        '''上海崇明,121.4,31.73|
        '''云南昆明,102.73,25.04|
        '''云南富民,102.48,25.21|
        '''云南晋宁,102.58,24.68|
        '''云南呈贡,102.79,24.9|
        '''云南安宁,102.44,24.95|
        '''云南昭通,103.7,29.32|
        '''云南永善,103.63,28.22|
        '''云南大关,103.91,27.74|
        '''云南彝良,104.06,27.61|
        '''云南鲁甸,103.54,27.21|
        '''云南绥江,103.97,28.58|
        '''云南盐津,104.28,28.08|
        '''云南威信,105.05,27.85|
        '''云南镇雄,104.86,27.42|
        '''云南巧家,102.92,26.9|
        '''云南永富,104.38,28.62|
        '''云南 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CityLocation() As String
            Get
                Return ResourceManager.GetString("CityLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property FSW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FSW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property night() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("night", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property night2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("night2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property night3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("night3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property night4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("night4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Preloader_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Preloader_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property satelite_weather() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("satelite weather", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property satelite_weather_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("satelite weather-blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CLEAR_DAY:晴天|
        '''CLEAR_NIGHT:晴夜|
        '''PARTLY_CLOUDY_DAY:多云|
        '''PARTLY_CLOUDY_NIGHT:多云|
        '''CLOUDY:阴|
        '''RAIN:雨|
        '''SNOW:雪|
        '''WIND:风|
        '''FOG:雾| 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property skyCon() As String
            Get
                Return ResourceManager.GetString("skyCon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {
        '''    &quot;status&quot;:&quot;ok&quot;,
        '''    &quot;lang&quot;:&quot;zh_CN&quot;,  
        '''    &quot;server_time&quot;:1443418222,
        '''    &quot;tzshift&quot;:28800, 
        '''    &quot;location&quot;:[
        '''        25.1552, 
        '''        121.6544 
        '''    ],
        '''    &quot;unit&quot;:&quot;metric&quot;, 
        '''    &quot;result&quot;:{
        '''        &quot;status&quot;:&quot;ok&quot;,
        '''        &quot;temperature&quot;:28.0,  
        '''        &quot;skycon&quot;:&quot;RAIN&quot;,  
        '''        &quot;pm25&quot;: 11,       
        '''        &quot;cloudrate&quot;:0.51,  
        '''        &quot;humidity&quot;:0.92,  
        '''        &quot;precipitation&quot;:{  
        '''             &quot;nearest&quot;:{ 
        '''                 &quot;status&quot;:&quot;ok&quot;,
        '''                 &quot;distance&quot;:0.77, 
        '''                 &quot;intensity&quot;: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TestCaiyunapi() As String
            Get
                Return ResourceManager.GetString("TestCaiyunapi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 中雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("中雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 中雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("中雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 冻雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("冻雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 冻雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("冻雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 多云() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("多云", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 多云_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("多云_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 大暴雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大暴雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 大暴雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大暴雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 大雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 大雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 大雪() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大雪", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 大雪_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大雪_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 小雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 小雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 小雪() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小雪", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 小雪_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小雪_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 强沙尘暴() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("强沙尘暴", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 强沙尘暴_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("强沙尘暴_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 晴() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("晴", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 晴_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("晴_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 暴雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("暴雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 暴雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("暴雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 暴雪() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("暴雪", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 暴雪_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("暴雪_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 沙尘() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("沙尘", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 沙尘_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("沙尘_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 沙尘暴() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("沙尘暴", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 沙尘暴_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("沙尘暴_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 特大暴雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("特大暴雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 特大暴雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("特大暴雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 阴天() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阴天", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 阴天_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阴天_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 阵雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阵雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 阵雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阵雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 阵雪() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阵雪", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 阵雪_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("阵雪_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 雷阵雨() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雷阵雨", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 雷阵雨_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雷阵雨_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 雾() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雾", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 雾_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("雾_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
